global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']

  - job_name: 'nginx'
    static_configs:
      - targets: ['host.docker.internal:9113']